
import SCons
env = Environment()

sources = []

sources += ['impl.c']

#lib = env.SharedLibrary('filestat', source = sources)
lib = env.StaticLibrary('filestat', source = sources)
bin = env.Program('test_lib.c', LIBS=['filestat', 'pthread'], LIBPATH='.')
